name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json

      - name: Instalar dependências Composer
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Validar composer.json
        run: composer validate --strict

      - name: Checar sintaxe PHP
        run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

      - name: Checar templates
        run: |
          test -f templates/promotional.html || exit 1
          test -f templates/newsletter.html || exit 1
          test -f templates/modern.html || exit 1
          test -f templates/notificacaoteiacrm.html || exit 1

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json

      - name: Instalar dependências Composer (produção)
        run: composer install --no-interaction --prefer-dist --no-progress --no-dev --classmap-authoritative

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          exclude: |
            .git*
            .github*
            node_modules/
            deploy.yml